ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.whale_sell]
path = "out/WhaleSellTrap.sol/WhaleSellTrap.json"
response_contract = "0xD7BfF196Ea7080593807869d78a5A3E7909E29eC"   # replace after deployment
response_function = "respondToWhaleSell(uint256,uint256,uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 5
private_trap = true
whitelist = []
